# When configuring filebeat-oss to communicate with AWS Elasticsearch on version 7.x (7.1.1 used)
# This ilm module needs to be disabled to prevent x-pack authorisation errors during startup
setup.ilm.enabled: false

#=========================== Filebeat inputs =============================

filebeat.inputs:

# Each - is an input. Most options can be set at the input level, so
# you can use different inputs for various configurations.
# Below are the input specific configurations.

- type: log

  # Change to true to enable this input configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
     - /opt/spg/servicemix/data/spg-audit/spg-audit.log

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

#==================== Elasticsearch template setting ==========================

setup.template.name: "spg-audit"
setup.template.pattern: "spg-audit-*"
setup.template.settings:
  index.number_of_shards: 1

#================================ Outputs =====================================

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["https://vpc-ndst-elk-audit-stack-6uwzfvrz5qzoi4hijmpepal5z4.eu-west-2.es.amazonaws.com:443"]
  index: "spg-audit-%{[agent.version]}-%{+yyyy.MM.dd}"
  pipeline: "spg-audit"

#================================ Processors =====================================
# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
